name: bareform
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - gdown
  - matplotlib
  - numpy
  - pillow
  - pytorch
  - scipy
  - torchvision
  - tqdm
  - pip
    